spring.application.name=autotrader
server.port=9090
#fyers.client-id=3CJ0ZQGMCY-100
#fyers.secret-key=BUBG6C7R8M
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

fyers.client-id=352DIVUSPJ-200
fyers.secret-key=5m7kdqyCM4aEUMxr

# SQLite database
spring.datasource.url=jdbc:sqlite:../store/autotrader.db
spring.datasource.hikari.connection-init-sql=PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL;
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Telegram notifications
telegram.bot-token=8707863423:AAEjX4Vi6uASb-wd02ErrqfqmqJXs6QCP-8
telegram.chat-id=5747395105
telegram.enabled=true